### ISSUE TITLE
Is it possible to use input without hair color map?

### ISSUE THREAD

**Issue by Kitty-sunray** [pit-ray/SPADE-pix2pix-for-Anime#3]
Hello!
Is it possible to use input without hair color map? 
Thanks!

**Comment by pit-ray** [comment]
It support such behavior after the latest commit.
When you place 256x256 images into predict_from, output with a random hair color. 
Thanks.

**Comment by Kitty-sunray** [comment]
Thanks for quick answer!

**Comment by pit-ray** [comment]
Oh, I'm sorry. You want to use the RGB image of the anime-type as the style. Semantic labels are also RGB, so I was mistaken.

I don't follow state-of-the-art GANs, so I don't know much about recent pix2pix. However, the pix2pix with SPADE in this repository does not use the style control by KL divergence shown in the original paper. Ideally, as you say, full-color anime images should be used by encoders to compute noise and learn latent representation. However, since I do not have enough computational resources, I could not generate a synthetic anime image using both a semantic map and a style image as the target with encoders.

Therefore, in this repository, instead of learning styles, only hair is learned in a small network, so no anime-type images are used as input for the generator as a target style.

I think the recent trend of generating images from semantic maps is probably to reproduce the pen that generates hair, eyes, etc. in drawing software. It seems to me that this is probably a more interesting application than regenerating the same images. 

I'm sorry if I'm missing the point as I don't fully understand your question.

**Comment by Kitty-sunray** [comment]
Thank you for answer.

**Comment by pit-ray** [comment]
Sorry for the late reply.

I have often heard of things like AnimeGAN2 which converts images to anime style.

SPADE is a method to restrict the loss of semantic information when generating images from Semantic maps. So I am not sure if the same effect can be theoretically performed for an image obtained from a camera. Even if the accuracy is improved, the fact may be due to an increase in the number of parameters.

Thanks for all the discussion. If you have any other questions, please let me know.

The answer to this question of whether my model will produce the desired results with the input image from the camera is **NO**.

Thanks.
